### ISSUE TITLE
affine options to save a view

### ISSUE THREAD

**Issue by VolkerH** [nvladimus/npy2bdv#1]
Hi,
thanks for making this public. I think this will be quite useful to me. I'm after creating BigStitcher datasets files directly from python. I know the tiling pattern and the approximate overlap of multiple tiles from a SPIM, would you consider adding the option to optionally pass in the affine transform parameters for each view (currently you pass in the `dx`,`dy`,`dz` as far as I could see?

**Comment by nvladimus** [comment]
Hi! Yes, I will add this, it's a good feature to have. Stay tuned!

**Comment by nvladimus** [comment]
Added along with simple example (shearing along X axis), check it out.

**Comment by VolkerH** [comment]
Hi, 

thanks. I just found some time to play with the library and test the affine transform. 
For a single dataset in the `.xml` it works fine. 

However, when I add several dataset there is no option to associate a separate affine transform for each. All datasets are assigned the same affine transform. 
To make it useable for generating moasics or something that is already coarsely aligned (e.g. from stage position metadata) to then refine in BigStitcher, one would have to be able to specify a separate affine transform for each dataset. 

I'm just reading through the code to see how that could be done in an elegant way.
