### ISSUE TITLE
Bug with append_substack()?

### ISSUE THREAD

**Issue by adamkglaser** [nvladimus/npy2bdv#17]
Was working with npy2bdv this past week and I think there may be a bug with append_substack()?

I think these lines:
https://github.com/nvladimus/npy2bdv/blob/e7bdce7d88aa12e2329244b76bcaff9d58685b09/npy2bdv/npy2bdv.py#L444-L446

Should include downsampling in the indices such as?
```
sub_z_start = int(z_start/2**ilevel)
sub_y_start = int(y_start/2**ilevel)
sub_x_start = int(x_start/2**ilevel)
dataset[sub_z_start : sub_z_start + subdata.shape[0],
        sub_y_start : sub_y_start + subdata.shape[1],
        sub_x_start : sub_x_start + subdata.shape[2]] = subdata
```

**Comment by nvladimus** [comment]
Hi, Adam! 
Good catch, indeed! I will fix it and write some tests to make sure it is solved.

**Comment by nvladimus** [comment]
Fixed, [pushed ](https://github.com/nvladimus/npy2bdv/commit/75d6f5dda900b4a132da5bce7fc429029d2d166e) to master.
