### ISSUE TITLE
Example of writing tiles with overlap request

### ISSUE THREAD

**Issue by Sh4zKh4n** [nvladimus/npy2bdv#4]
I wondered if you could provide an example of overlapping tiles for h5 conversion?

I can see you have channels, angles and so forth. What if you had some overlapping tiles that needed correlation bigstitcher? I can see you can add the views and in the code you have tiles, but there really isnt and examples of this. I am not sure if the tile should be a tuple (though it doesnt look like it) or an in of where it is. Being able to convert to the bigstitcher format that has some of the overlap already completed with the speed of writing here could be a big help.

**Comment by nvladimus** [comment]
Hi,
Good question - I added a new **Example 3.1** in the [notebook](https://github.com/nvladimus/npy2bdv/blob/master/npy2bdv/examples.ipynb). The tiles do not overlap in the example, they match perfectly. Making them overlap by (X, Y, Z) pixels is done simply by offsetting the last column by (X, Y, Z) of the transformation matrix one writes into XML.

I hope this helps!

**Comment by Sh4zKh4n** [comment]
Hi @nvladimus , thanks for the example. Just to make sure I am getting this right, do you mean the last 4th column  of the following matrix?:

```python
unit_matrix = np.array(((1.0, 0.0, 0.0, 0.0), # change the 4. value for x_translation (px)
                        (0.0, 1.0, 0.0, 0.0), # change the 4. value for y_translation (px)
                        (0.0, 0.0, 1.0, 0.0)))# change the 4. value for z_translation (px)
````

And thatthe value should be changed to pixel overlap? Thats great! One last thing, I know this is a bit annoying. The file here is written out to a HDF file format. The tiles themselves havent actually been tranformed into a fused image and that they are seperate volumes? The reason I ask, is that I was looking for a way to get some zarr files into big stitcher, so this looks as a great option. I just have to work out the specifics of the output. Will have a go but would be interested to know your thoughts. Thanks for the example!

**Comment by nvladimus** [comment]
Hi,
Yes, the last column of this matrix is the translation term. This particular `unit_matrix` does not do any transformation, but if you set, say,  `unit_matrix[0,3]=100`, the tile will be moved by +100 px in space. The pixel overlap is something specific to a particular imaging experiment. This library cares only about is the transformations of individual views. If you know the space coordinates of your tile, plug them into the 4.th column of this matrix, and BigStitcher will know where to put the tile in space.

Re: second question, yes, the tiles `are separate volumes` in the H5 file.
You are welcome!

**Comment by Sh4zKh4n** [comment]
That's great,  right I get the transformation matrix now. Will try this out later tonight, will be interesting to see the speed of write. It should save time in copying to different hdf5 files then playing around with the file names to get the gridding. That's really helpful.

**Comment by Sh4zKh4n** [comment]
Sorry to be a pain, so I ran the example thats fine, but when I try to understand it. You have a singular test image that you are tiling. Do you create a list of ndarrays and substitute into stack? Im being a bit slow here to understand where the stack of numpy arrays go. Very sorry to be annoying here.

**Comment by nvladimus** [comment]
No worries! I create each tile on the fly by slicing the stack array:
```
tile_stack = stack[:, j*tile_h:(j+1)*tile_h, i*tile_w:(i+1)*tile_w]
```
Then write each tile as a view:
```
bdv_writer.append_view(tile_stack,...
```
I could write it into a longer (and uglier) code to break down individual steps, but I tried to be brief, therefore the code is a bit dense. You can e.g. insert `print(j*tile_h)` etc. into the loop to see how the `stack` is being sliced, and save and plot individual tiles using matplotlib.

**Comment by Sh4zKh4n** [comment]
Ok perfect, good I wasn't being stupid! I have multiple columns and I think with the virtual stack method with appending, it should work. Will try again to tomorrow and either share here and/or the image forum. Thanks for helping ! I have to say the write was fast, I thought something had gone wrong until I realised it was really fast on the write to me external ssd!

**Comment by nvladimus** [comment]
You are welcome!
