### ISSUE TITLE
Read affine transform from XML

### ISSUE THREAD

**Issue by dpshepherd** [nvladimus/npy2bdv#6]
Hi Nikita!

For our OPM post-processing, it will be useful to read the affine transform that contains the stage coordinates back out for the tiled acquisition. Right now we write using the virtual stack with no downsampling and write the stage coordinates to the affine translation column.

For post-processing, we read each big strip scan (~100,000x1600x256) back in to deconvolve, deskew, and split it into smaller blocks. We then write a new H5 with downsampling for stitching. We need to transform the stage coordinates after the deskew and splitting for each new tile.

I took a quick look at the new BdvEditor class and I think this should be simple to implement. We will take a shot at it implementing it and do a pull request, but I I wanted to let you know in case you have any input before we get started on it.

Thanks,
Doug

**Comment by nvladimus** [comment]
Hi, Doug,
Yes, this should be quite straightforward to implement, let me know if you need any help. If you have time, please also consider writing a quick test for it, e.g. by adding a function similar to [test_view_properties()](https://github.com/nvladimus/npy2bdv/blob/e857c0915f30b4ae0fb3f73f74060f735124ef31/test/test_h5.py#L64), to make sure it works as intended. Thanks!

**Comment by dpshepherd** [comment]
Will do! Thanks!

**Comment by nvladimus** [comment]
Hi, Doug,
I added `.read_affine(...)` method to both classes `BdvWriter()` and `BdvReader()`. Also, appending an affine transform is possible now in both classes.
See e.g. unit test [here](https://github.com/nvladimus/npy2bdv/blob/0a691ed8728d553dbcc6cae7ef68470e13fa11c7/test/test_h5.py#L94) and docs [here](https://nvladimus.github.io/npy2bdv/npy2bdv.html#npy2bdv.npy2bdv.BdvBase.read_affine). I hope this is useful!

**Comment by dpshepherd** [comment]
Hi Nikita,

Shoot, we wrote the functions but hadn't had time to write the tests. Sorry
for being so slow! Things got busy again with the semester starting and I
forgot to keep track of this.

Thank you!!

**Comment by nvladimus** [comment]
You are welcome!
